name: Deploy Infrastructure with Terraform

on:
  push:
    paths:
      - 'infra/**'
      - '.github/workflows/terraform-deploy.yml'
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      working-directory: infra
      run: terraform init

    - name: Terraform Import Existing Resource Group
      working-directory: infra
      run: terraform import azurerm_resource_group.this /subscriptions/7dd2d1d5-754a-46c8-a353-0892e75dcc3f/resourceGroups/bexio-rg

    - name: Terraform Import Existing Storage Account
      working-directory: infra
      run: terraform import azurerm_storage_account.this /subscriptions/7dd2d1d5-754a-46c8-a353-0892e75dcc3f/resourceGroups/bexio-rg/providers/Microsoft.Storage/storageAccounts/bexiostorage67073

    - name: Terraform Plan
      working-directory: infra
      run: terraform plan

    - name: Terraform Apply
      working-directory: infra
      run: terraform apply -auto-approve
